### ISSUE TITLE
Can't get install working

### ISSUE THREAD

**Issue by ghost** [Rob-murphys/ribdif#1]
Hi there! I executed the steps listed in the readme to create a conda environment and install RibDif2 and its dependencies, then tried to run: 

ribdif -g Ruegeria

But I get the following output, including an odd error I don't know how to handle: 

RibDif v(2, 0, 0)                                                               
                                                                                
Input command:                                                                  
ribdif -g Ruegeria                                                              
                                                                                
#============================================================#                  
#== RibDif2 is running on: Ruegeria in the bacteria domain ==#
#============================================================#

#= Parsing arguments =#

#= All arguments resolved =#

Downloading all genome records of Ruegeria from NCBI at complete assembly level

10 genomes of Ruegeria were downloaded

Modifying fasta headers.

#= Running barrnap on downloaded sequences =#

Skipping detailed intra-genomic analysis and ANI (if needed, use -a/--ANI).

Alligning full-length 16S genes within genomes with muscle.

Skipping alignments and tree generation for 16S rRNA genes (if needed, use -m/--msa).

#= Generating amplicon sequences =#

Making unique clusters with vsearch.

Making reports and figures

Skipping total amplicon alignment and diversity calculation

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/site-packages/ribdif/utils.py", line 190, in make_reports
    plot_clus, cluster_df = figures.cluster_heatmap(cluster_dict, row_palette, species_series)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/site-packages/ribdif/figures.py", line 34, in cluster_heatmap
    row_clus = fastcluster.ward(np.where(cluster_df > 0, 1, 0))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/site-packages/fastcluster.py", line 62, in ward
    return linkage(D, method='ward')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/site-packages/fastcluster.py", line 247, in linkage
    linkage_wrap(N, X, Z, mthidx[method])
TypeError: argument 2 must be numpy.ndarray, not numpy.ndarray
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rye/miniconda3/envs/ribdif2/bin/ribdif", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/site-packages/ribdif/__main__.py", line 389, in main
    pool.starmap(utils.make_reports, zip(names, repeat(args.msa), repeat(outdir), repeat(genus), repeat(logger), repeat(args.user), repeat(unique_species), repeat(all_species), repeat(genome_count)))
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rye/miniconda3/envs/ribdif2/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: argument 2 must be numpy.ndarray, not numpy.ndarray

**Comment by Gsegui** [comment]
I am having the same issue.  Have anyone find the solution?

**Comment by mikaells** [comment]
Sorry for this issue - it comes from an external update and is poorly handled by our installation approach. We'll make a more robust installation very soon.

In the meantime, this should work. After a standard install, make sure you are in the conda environment and then run:
conda install numpy==1.26.4
